### ISSUE TITLE
Доработка CSS

### ISSUE THREAD

**Issue by ultrakiwi99** [ultrakiwi99/bond_delivery_form#12]
- Выравнивание по левому краю
- Плавное разворачивание карточек

**Comment by tsol** [comment]
Можно ректанглы куда ставятся галочки сделать квадратными, а не прямоугольными. Немного не эстетично.

**Comment by tsol** [comment]
В заказе надо сделать удаление и цену более красиво. Сейчас цена и крестик в куче, нужно цену сдвинуть левее, отдельно сделать иконку удаления больше по размеру.
Все добавки писать более мелким шрифтом под самим товаром, возможно сереньким.
