### ISSUE TITLE
Массив Variants в модификаторе

### ISSUE THREAD

**Issue by tsol** [ultrakiwi99/bond_delivery_form#13]
сиропов будет 16, хотелось бы что б они отмечались как кнопки в тасках
 
типа выбираешь сиропы + 29 рублей галочкой - 
Открывается список кнопок - float:left кнопок, либо белых либо синих если выбраны
По типу как выбор размеров сейчас, только множественный и с переносом на следующую строку. Было бы красиво, если бы они были одной ширины и таким образом ровненько вставали таблицей.

Если текст больше, чем ширина, то с помощью css красиво его подрезать.

**Comment by ultrakiwi99** [comment]
>Если текст больше, чем ширина, то с помощью css красиво его подрезать.
Красиво это как?
