### ISSUE TITLE
снова CSS выравнивания, промежутки, переносы

### ISSUE THREAD

**Issue by tsol** [ultrakiwi99/bond_delivery_form#19]
Все выравнивания по левому краю должны быть выравненны - одна вертикальная линия.
Начало кнопок, тексты, заголовки и прочее. И правее все, меньше паддинг. Как у питчера. 
Исключения - только в заказе добавки со сдвигом.
 
Margin над молоко и добавить - визуальное разделение разделов
 
Галочку - квадратную, не прчмоугольную (у нее еще размер гуляет в зависимости от заполненности строки)

С ценами придумать в добавка, что б они не упрыгивали

Ориентируемся на питчер

**Comment by ultrakiwi99** [comment]
В питчере цена добавок двигается в зависимости от длины названия добавки.
