### ISSUE TITLE
В приложении нет localStorage, т.к. браузер запускается в тюрьме

### ISSUE THREAD

**Issue by tsol** [ultrakiwi99/bond_delivery_form#33]
нужно сохранение по номеру телефона через апи

**Comment by tsol** [comment]
локал стораж можно оставить для всего, отлавливая исключения - он будет отлично работать когда форма открыта с сайта.

если же есть гет параметр номер телефона, то по нему надо сохранять адрес и выбранную точку по апи в момет посылки емейла, а восстанавливать асинхронным аякс запросом в Menu.mounted

**Comment by ultrakiwi99** [comment]
А куда сохранять-то?
Сделать таблицу cb_delivery_clients?

**Comment by tsol** [comment]
да, таблицу. 

Адрес и точку доставать только, когда параметры переданы в ГЕТ запросе, желательно по комбинации
номер карты + номер телефона.

Если дергать адрес из апи по номеру телефона после заполнения формы, можно дать злоумышленнику возможность по номеру узнать адрес нашего клиента.
