### ISSUE TITLE
С телефона невозможно написать комментарий к товару и тут же добавить товар

### ISSUE THREAD

**Issue by tsol** [ultrakiwi99/bond_delivery_form#63]
Требуется кликать в какое-то место на карточке товара, что не так просто.
Из-за того, что текстария адаптивная и прыгает туда сюда - на кнопку добавить не нажать чисто по человечески после заполнения коммента.

Пусть бует себе ширинойй в одну строку... если текст по факту соержит переносы строк, тогда и количество rows можно увеличить.

текущее поведение надо переделать

**Comment by ultrakiwi99** [comment]
Может быть модальное окно сделать.
